Try updating Django, add CI
- Two tests are failing locally:
```
FAILED anno/tests/test_annojs.py::test_to_annotatorjs - AssertionError: assert False
FAILED anno/tests/test_crud.py::test_remove_in_2step - ValueError: 'Anno' instance needs to have a primary key value before this relationship can be used.
```