Fix to pass anno/tests/test_crud/test_remove_in_2step
Was failing - I think the queryset items are just pointers so if they are deleted you can't do much with them?

ValueError: 'Anno' instance needs to have a primary key value before this relationship can be used.

anno/crud.py:662: in delete_annos
    success.append(a.serialized)
anno/models.py:138: in serialized
    s['totalReplies'] = self.total_replies
anno/models.py:117: in total_replies
    return self.anno_set.all().filter(anno_deleted=False).count()
/usr/local/lib/python3.9/site-packages/django/db/models/manager.py:164: in all
    return self.get_queryset()